apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finops.fullname" . }}-secrets
  labels:
    {{- include "finops.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.gateway.env.JWT_SECRET | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  clickhouse-password: {{ .Values.clickhouse.auth.password | default "" | quote }}
  huawei-access-key: {{ .Values.ingestion.env.HUAWEI_ACCESS_KEY | default "" | quote }}
  huawei-secret-key: {{ .Values.ingestion.env.HUAWEI_SECRET_KEY | default "" | quote }}
