apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finops.fullname" . }}-secrets
  labels:
    {{- include "finops.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.gateway.env.JWT_SECRET | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
